export const streamerList = [
  {
    nickName: "Elraenn",
    name: "Tuğkan Gönültaş",
    followerCount: 3700000,
    birthYear: 1994,
    category: "E-Spor",
  },
  {
    nickName: "wtcN",
    name: "Ferit Karakaya",
    followerCount: 2900000,
    birthYear: 1991,
    category: "E-Spor",
  },
  {
    nickName: "KendineMuzisyen",
    name: "Kemal Can Parlak",
    followerCount: 2700000,
    birthYear: 1992,
    category: "Müzik",
  },
  {
    nickName: "Pqueen",
    name: "Pelin Baynazoğlu",
    followerCount: 2500000,
    category: "Sohbet",
  },
  {
    nickName: "UNLOSTV",
    name: "Cantuğ Özsoy",
    followerCount: 2400000,
    category: "E-Spor",
  },
  {
    nickName: "Jahrein",
    name: "Ahmet Sonuç",
    followerCount: 2300000,
    category: "Sohbet",
  },
  {
    nickName: "Mithrain",
    name: "Eray Gündoğdu",
    followerCount: 2200000,
    category: "E-Spor",
  },
  {
    nickName: "Elwind",
    name: "Emre Yılmaz",
    followerCount: 2100000,
    category: "E-Spor",
  },
  {
    nickName: "Levo",
    name: "Levent Özer",
    followerCount: 1900000,
    category: "E-Spor",
  },
  {
    name: "Seren Sarikaya",
    followerCount: 1800000,
    category: "Müzik",
  },
  {
    name: "Uğur Çiftçi",
    followerCount: 1700000,
    category: "E-Spor",
  },
  {
    name: "Berkcan Güven",
    followerCount: 1600000,
    category: "Sohbet",
  },
  {
    nickName: "TheRealUfuk",
    name: "Ufuk Öztürk",
    followerCount: 1500000,
    category: "Sanat & El Sanatları",
  },
  {
    nickName: "Barbaros",
    name: "Barbaros Yavuz",
    followerCount: 1400000,
    category: "MMO",
  },
  {
    nickName: "Woahzelot",
    name: "Çağrı Kocabaş",
    followerCount: 1300000,
    category: "MMO",
  },
  {
    nickName: "HasanAbi",
    name: "Hasan Peker",
    followerCount: 1200000,
    category: "E-Spor",
  },
  {
    name: "Esra Ayyıldız",
    followerCount: 1100000,
    category: "Sohbet",
  },
  {
    name: "Enes Batur",
    followerCount: 18900000,
    birthYear: 1996,
    category: "Komedi, Oyun",
  },
  {
    name: "Orkun Işıtmak",
    followerCount: 15400000,
    birthYear: 1988,
    category: "Komedi, Sketç",
  },
  {
    name: "Ruhi Çenet",
    followerCount: 14100000,
    birthYear: 1982,
    category: "Eğlence, Sohbet",
  },
  {
    name: "Oğuzhan Uğur",
    followerCount: 13900000,
    birthYear: 1993,
    category: "Komedi, Vlog",
  },
  {
    name: "Barış Özcan",
    followerCount: 12900000,
    birthYear: 1986,
    category: "Sohbet, Röportaj",
  },
  {
    name: "Danla Bilic",
    followerCount: 12700000,
    birthYear: 1994,
    category: "Moda, Güzellik",
  },
  {
    name: "Merve Özkaynak",
    followerCount: 12400000,
    birthYear: 1991,
    category: "Müzik",
  },
  {
    name: "Burak Yılmaz",
    followerCount: 12200000,
    birthYear: 1985,
    category: "Futbol",
  },
  {
    name: "Batuhan Karadeniz",
    followerCount: 11900000,
    birthYear: 1992,
    category: "Komedi, Sketç",
  },
];
